AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "**/*.golf.rb"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
